/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 new-balance.gltf --transform 
Files: new-balance.gltf [4.92KB] > C:\Users\P4ppy\Coding\r3f-drei-proj\public\new-balance-transformed.glb [1.14MB] (-23168%)
Author: Lassi Kaukonen (https://sketchfab.com/thesidekick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/new-balance-680-v7-f4828975332845829c179a24001caeb8
Title: New Balance 680 V7
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/new-balance-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/new-balance-transformed.glb')
