/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [4.62KB] > C:\Users\P4ppy\Coding\r3f-drei-proj\public\nike_air_mag\air-mag-transformed.glb [775.35KB] (-16682%)
Author: pandan (https://sketchfab.com/pandan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-mag-15ef47bad0aa4666b459cf78261abce5
Title: Nike Air Mag
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function AirMag(props) {
  const { nodes, materials } = useGLTF('/nike_air_mag/air-mag-transformed.glb')
  const ref = useRef()
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    ref.current.rotation.set(0.01 + Math.cos(t / 20) / 10, Math.sin(t / 4) / 4, 0)
    ref.current.position.y = (1 + Math.sin(t / 10)) / 10
  })
  return (
    <group 
      {...props} 
      dispose={null} 
      ref={ref} 
      scale={0.05}>
      <mesh 
        geometry={nodes.Object_2.geometry} 
        material={materials.StingrayPBS1SG} 
        position={[0, 15, 0]} 
        rotation={[Math.PI / 2, 3, 0]}  />
    </group>
  )
}

useGLTF.preload('/nike_air_mag/air-mag-transformed.glb')
